print("Sek - Runtime Cloud Security and Misconfiguration Scanning")
print("-----")
print("Scan")
print("-----")
print("Cloud: AWS - Service: EKS - Name: test")
print("-----")
print("Results")
print("-----")
print("service-logging: PASS")
print("service-secrets: PASS")
print("service-endpoint: PASS")
print("service-endpoint-firewall: PASS")
print("service-security-groups: PASS")
print("nodes-imds: PASS")
print("nodes-volumes: PASS")
print("nodes-security-groups: PASS")
print("nodes-subnets: PASS")
print("nodes-ips: PASS")
print("-----")
print("Stats")
print("-----")
print ("Time: 0.5s")
print("Checks: 10")
print("Passed: 10 - (100.00%)")
print("Failed: 0 - (0.00%)")
print("Skipped: 0 - (0.00%)")
print("Errors: 0 - (0.00%)")
